package:
  name: fontconfig
  version: 2.11.1
  www: http://fontconfig.org/
  short: Fontconfig is a library for configuring and customizing font access.

download:
  url: http://fontconfig.org/release/
  file_tar_bz2: ~
  checksum: dc62447533bca844463a3c3fd4083b57c90f18a70506e7a9f4936b5a1e516a99

version:
  installed_sh_trailing: fc-list --version

linux:

  - build:
    - configure_kx: --disable-static --disable-docs
    - make: ~

  - test:
    - check: ~
 
  - install:
    - install: ~
    - echo: "Install man pages"
    - sh: |
        install -v -m644 fc-*/*.1          /share/man/man1
        install -v -m644 doc/*.3           /share/man/man3
        install -v -m644 doc/fonts-conf.5  /share/man/man5
    - sh: |
        ln -svf /share/fontconfig/conf.avail /etc/fonts/conf.avail

verify_cli: |
  kx_cli_match_success fc-list { /share/fonts/X11/ /usr/share/fonts/TTF/ }
  kx_cli_match_success "fc-cat --version" { fontconfig version }
  kx_cli_success fc-validate /share/fonts/cantarell/Cantarell-Regular.otf
