package:
  name: xkeyboard-config
  version: 2.16


download:
  url: http://xorg.freedesktop.org/releases/individual/data/xkeyboard-config
  file_tar_bz2: ~
  checksum: 1e8a1f212c96b7f71ca0b05da361cac1816d27baae1d8e03e7b53049b58d1d58

version: ~

linux:

  - build:
    - configure_kx: >
        --with-xkb-rules-symlink=xorg
        --enable-compat-rules=yes
    - make: ~

  # 'make check' does nothing

  - install:
    - install: ~     

